{
 "title": "Tokio Task List",
 "description": "Tokio Console Tasks Overview",
 "tags": [
  "tokio",
  "rust",
  "async",
  "task-list"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tokio_tasks_total", "legendFormat": "Total Tasks" }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tokio_task_state{state=\"running\"})",
     "legendFormat": "Running Tasks"
    }
   ]
  },
  {
   "title": "Idle Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tokio_task_state{state=\"idle\"})",
     "legendFormat": "Idle Tasks"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tokio_task_state{state=\"completed\"})",
     "legendFormat": "Completed Tasks"
    }
   ]
  },
  {
   "title": "Task Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (task_location) (tokio_task_polls_total)"
    }
   ]
  },
  {
   "title": "95th Percentile Busy Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tokio_task_busy_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile Busy Time"
    }
   ]
  },
  {
   "title": "Total Waker Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(tokio_task_waker_count)", "legendFormat": "Total Waker Count" }
   ]
  }
 ]
}