global:
  scrape_interval: 10s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tokio-console-exporter'
    static_configs:
      - targets: ['you-end-point-here:9090']
    metrics_path: /metrics
    honor_labels: true
    scrape_interval: 10s
    scrape_timeout: 9s
