name: Build Linux Binary

on:
  release:
    types: [published, created]
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Build release binary
      run: |
        cd tokio-console-prometheus-exporter
        cargo build --release --target x86_64-unknown-linux-gnu

    - name: Debug build output
      run: |
        echo "Checking build output..."
        ls -la tokio-console-prometheus-exporter/target/x86_64-unknown-linux-gnu/release/
        echo "Binary name should be: tokio_console_exporter"

    - name: Create release directory
      run: |
        mkdir -p release
        cp tokio-console-prometheus-exporter/target/x86_64-unknown-linux-gnu/release/tokio_console_exporter release/
        cp tokio-console-exporter.service release/
        cp -r monitoring release/
        cp README.md release/

    - name: Create archive
      run: |
        cd release
        tar -czf tokio-console-prometheus-exporter-linux-x86_64.tar.gz *
        cd ..

    - name: Upload artifact (Manual builds)
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: tokio-console-prometheus-exporter-linux-x86_64
        path: release/tokio-console-prometheus-exporter-linux-x86_64.tar.gz
        retention-days: 30

    - name: Create Release
      if: github.event_name == 'release'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: ${{ github.event.release.name }}
        body: ${{ github.event.release.body }}
        draft: false
        prerelease: ${{ github.event.release.prerelease }}

    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/tokio-console-prometheus-exporter-linux-x86_64.tar.gz
        asset_name: tokio-console-prometheus-exporter-linux-x86_64.tar.gz
        asset_content_type: application/gzip
