name: Build Linux Binary

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Build release binary
      run: |
        cd tokio-console-prometheus-exporter
        cargo build --release --target x86_64-unknown-linux-gnu

    - name: Create release directory
      run: |
        mkdir -p release
        cp tokio-console-prometheus-exporter/target/x86_64-unknown-linux-gnu/release/tokio-console-exporter release/
        cp tokio-console-exporter.service release/
        cp -r monitoring release/
        cp README.md release/

    - name: Create archive
      run: |
        cd release
        tar -czf tokio-console-prometheus-exporter-linux-x86_64.tar.gz *
        cd ..

    - name: Upload artifact (Manual builds)
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: tokio-console-prometheus-exporter-linux-x86_64
        path: release/tokio-console-prometheus-exporter-linux-x86_64.tar.gz
        retention-days: 30

    - name: Upload to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
      with:
        files: |
          release/tokio-console-prometheus-exporter-linux-x86_64.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
